services:
  jenkins:
    container_name: jenkins_container
    image: jenkins/jenkins:lts
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - cicd_network
volumes:
  jenkins_home:
networks:
  cicd_network: